packaging-examples/rpm-based/postscriptbarcode.spec
rpm5 treats `#` as comment, and there's "better" export url from github that just works
=> do not use # as url

packaging-examples/rpm-based/postscriptbarcode.spec
in case macro does not exist, it's presented as whole string, i.e `%{_smp_mflags}`, but we want empty string
=> handle missing _smp_mflags macro

src/code128.ps
Check if last character is GS1-128 linkage flag and encode and exit.
Eg currently if in set C mode with a CC-A it encodes it as 2 switch characters (swb and swc) rather than a single swa (cf GS1 General Specifications standard Figure 5.9.8-9.).
=> Allow for GS1 CC linkage in code128 encoding loop

src/databarstackedomnicomposite.ps
Missing zero typo in array to clear 1st 4 modules of separator in DataBar Stacked Omnidirectional Composite, eg
`10 100 moveto ((01)0401234567890|(17)050101(10)ABC123) () /databarstackedomnicomposite /uk.co.terryburton.bwipp findresource exec` does not match GS1 General Specifications Figure 5.1-5. (4th module in composite separator shouldn't be set).
=> databar stacked omni composite missing 0 in clearing sep 1st 4 modules

src/code128.ps
E.g. `10 100 moveto ((91)1|(21)12) () /gs1-128composite /uk.co.terryburton.bwipp findresource exec` fails
=> Allow for GS1 CC LNK in code128 numsscr

src/gs1-cc.ps
For encodation method "11":
- sets mode to numeric only if no alphas, otherwise alphanumeric (avoids immediate shift in main loop)
- only deals with alpha in local encoding loop, leaves numeric/alphanumeric (and iso646, which isn't catered for in local loop) to main loop
- adds ~~numeric~~ alphanumeric shift after FNC1 when prefixing padding in alpha mode
These data sets show the issues:
`(1234567|(90)1ABC4) () /upcecomposite`, where "BC4" is encoded in alpha mode, prefixs padding with FNC1 but not with required ~~numeric~~ alphanumeric shift
`(1234567|(90)1AB34) () /upcecomposite`, where mode is set to numeric for "B34", causes an immediate switch to alphanumeric in main loop
`(1234567|(90)1AB+D) () /upcecomposite`, where iso646 "+" causes undefined in local loop
=> gs1-cc: method 11 leave non-alpha to main loop; +alphanum shift alpha pad

src/gs1-cc.ps, src/pdf417.ps
You may or may not be interested in this, which implements the GS1 General Specifications Section 5.9.2.3 guideline of rows <= 30 for CC-C.
- increases the `gpfenc` buffer by 8 to allow for the max 30x30 size
- loops in `rembits` until rows <= 30 or columns >= 30
- uses `cccolumns` so that it gets passed to pdf417 (along with `eclevel`)
- makes sure that `c` is defined in pdf417 if `columns` is > 30
Given the 30x30 limit, it means that the ECC has to be reduced from the recommended 64 to 32 for codeword counts near the max. This isn't mentioned or dealt with in the GS1 spec so it's debatable whether the conclusion is valid...
=> gs1-cc: rows <= 30, lower ECC near max, gpfenc buf increase; pdf417 c def

src/codablockf.ps
For codablockf improves setc switching by using the number runlength remaining in row (`remnums`) instead of the full runlength.
In particular this enables the reproduction of the 4-row example AIM ISS-X-24 Figure 1, which otherwise was taking 5 rows:
`2 100 moveto (CODABLOCK F 34567890123456789010040digit) (columns=8) /codablockf /uk.co.terryburton.bwipp findresource exec`
Also
- ensures `c` set and `rows` between limits
- increases `cws` buffer to allow for rows being greater than specified by setting it to max rows
- allows for `r` being greater than requested rows in last row determination
The last 3 issues can be triggered by setting e.g. rows=1 and/or rows=3
=> codablockf: remnums for setc switch, c set, rows & r check, cws buf

src/code2of5.ps
Sets `sbs` length correctly for `code2of5` by using stop char length rather than start. Non-functional as ignored by `renlinear` but stops `sbs` having -48 as last entry.
=> code2of5: set sbs length using stop char length

src/micropdf417.ps
This is purely for tidiness and completely non-functional but when integrating Zint testing for MICROPDF417 noticed that at the beginning of the datcws seq encode block in auto the state is set to Alpha Compaction when the default for micropdf417 is Byte. Obviously could just change this to Byte, however I don't think it matters here, unlike in the pdf417 case, as the seq array will always begin with a scalar latch, so the suggestion is to not set the state here at all.
=> micropdf417: don't bother setting state before auto datcws seq encode

src/code32.ps
E.g. `10 100 moveto (34567890) readonly () /code32 /uk.co.terryburton.bwipp findresource exec` fails
=> code32: use temp string for cvrs

src/databarlimited.ps, src/databarlimitedcomposite.ps
Adds 5 right guard spaces to databarlimited as specced by ISO/IEC 24724:2011 Section 6.2 (e) (second edition addition it appears), and adjusts the databarlimitedcomposite separator accordingly. For the latter
`20 100 moveto ((01)1311234567890|(17)010615(10)A123456) () /databarlimitedcomposite /uk.co.terryburton.bwipp findresource exec`
still reproduces Figure 5.9.2-1. in GS1 General Specifications v20.0 (Figure 1 in ISO/IEC 24723:2010).
=> databarlimited and composite 5 right guard spaces

src/pharmacode2.ps
For instance `/ret (8) (dontdraw) /pharmacode2 /uk.co.terryburton.bwipp findresource exec def ret /bhs get ==` has nulls at end.
=> pharmacode2: set bhs/bbs lengths exactly

src/databarexpandedstackedcomposite.ps
Missing zero typo in array to clear 1st 4 modules of separator in DataBar Expanded Stacked Composite, eg for
`10 200 moveto ((20)12|(21)1234) () /databarexpandedstackedcomposite /uk.co.terryburton.bwipp findresource exec` the 4th module (looks like 3rd because barcode begins with a space) in composite separator shouldn't be set (cf https://github.com/bwipp/postscriptbarcode/pull/118).
=> databarexpandedstackedcomposite: missing 0 in clearing sep 1st 4 modules

src/micropdf417.ps, src/pdf417.ps
For pdf417 and micropdf417 ECI handling:
- Allows for extra codewords in `seqlen`
- Missing `astore` in the 810900 - 811799 branch of `ence`
- Removes swapping of ECI from before to after mode switches
The last is based on interpreting Sections 5.5.3.2 and 5.5.3.4 of ISO/IEC 15438:2015 as meaning that within the mode the mentioned placements are the only ones valid, but that it's fine for an ECI to occur before (i.e. outside) the mode.
The Section 5.5.3.3 Byte Shift case without the change causes eg. `10 200 moveto (^ECI000009^226) (parse parsefnc) /pdf417 /uk.co.terryburton.bwipp findresource exec` to fail, which could be dealt with in the "Encode the sequence" loop instead, but it seems much more natural to solve it by not swapping...
=> pdf417/micropdf417 ECI: adjust seqlen, missing astore, remove swapping

contrib/development/gs1-format-spec.txt
Remove extraneous 4309, plus some adjustments spotted when running against the current Zint tests.
=> gs1-format-spec: 253/255 2nd optional; 4309 rm; 719 -> 714; 8005 fixed

contrib/development/gs1-format-spec.txt, src/gs1lint.ps, tests/ps_tests/gs1lint.ps
Missed this, (4308) does not use percent encoding.
=> gs1-format-spec: 4308 no pcenc

src/codeone.ps, tests/ps_tests/codeone.ps, tests/ps_tests/test.ps
Some Code One changes:
- lookup: adjusts count check for EDI (Step Q5) to be same as spec - was exiting EDI mode too early in a number of cases; also TEXT and C40 rounding added
- encCTX: adds missing ctxvals buffer transfers on numeric check exits
- encCTX: adds Steps E1c and E2 when in EDI mode
- encD: allows for 1 remaining codeword and some remaining bits on "Final codeword with no data" check; also adds check that no remaining bits if no codewords left
- encD: allows for being able to encode 2 digits in an ASCII double-digit on "Final codeword as ASCII" check (figures given in Table 2 data capacity are now met)
New test file "tests/ps_tests/codeone.ps".
=> codeone: lookup Q5; encCTX ctxvals missing, Steps E1c, E2; numD EOD checks

build/make_standalone
AFAICS, currently it's only possible to create a standalone file with a single encoder (and all its dependencies), while some applications may need to use a couple (in my case, at least 2 but maybe up to 4) different symbologies, so I've extended the script to allow creating a standalone file with just the encoders needed and am submitting it here in case it might be useful for others.
=> Allow creating standalone file with more than one encoder

build/make_standalone
This corrects a problem in the recent 6d673f6 (Extend make_standalone
script to allow for more than 1 encoder, 2021-02-12) which could (and
did) result in having duplicated dependencies in the generated files.
While this didn't seem to result in any problems, it is still at best
completely unnecessary.
Keep track of the dependencies we had already seen to prevent this from
happening.
---
Sorry, my [previous PR](https://github.com/bwipp/postscriptbarcode/pull/144) wasn't quite correct, so here is another one amending it slightly to avoid having duplicated sections in the output.
=> Avoid duplication in make_standalone with multiple encoders

contrib/development/gs1-format-spec.txt
Adds "# Data title" comments. Aligns them out to col 61, uses UTF-8 for squared and cubed, and expands out "410-417",  "710-714" and "8017-8018", but leaves "7030-7039" and "7230-7239", which I think are ok decisions but let us know!
=> gs1-format-spec: add "# Data title" comments

contrib/development/gs1-format-spec.txt, src/gs1lint.ps, tests/ps_tests/gs1lint.ps
Just changes missed 425 to be same as 423 (leaving key and other possibles (e.g. iban, couponcode) alone, as agree, pedantic and not very semantic plus can always do later).
=> gs1-format-spec: 425 -> N3..15 (same as 423)

src/azteccode.ps, tests/ps_tests/azteccode.ps, tests/ps_tests/test.ps
The issue is that e.g. `10 100 moveto (1. . . . . ) () /azteccode /uk.co.terryburton.bwipp findresource exec` fails as the "Optimise using P compression" block doesn't take into account that the `lastchar` may not be at the end of the sequence, due to intervening latches (U/L M/L P/L), so the `pcomp` replaces the wrong character (P/L).
The proposed change addresses that by checking the position of `lastchar` and moving it to the end. It also applies the optimisation to sequences not ending in P. For instance Figure I.1 left and right in ISO/IEC 24778:2008 are now reproduced as the D/L sequence uses P/S CRLF at the end instead of U/L M/L CR LF.
But it's a fair amount of code...
=> azteccode: allow for lastchar not at end in pcomp optimise

src/dotcode.ps, tests/ps_tests/dotcode.ps, tests/ps_tests/test.ps
Typo `add` -> `addtocws` in "Terminate to C" block in `encBIN`, e.g. `10 100 moveto (^128^1281234567890123456) (parse) /dotcode /uk.co.terryburton.bwipp findresource exec` fails.
=> dotcode: typo add -> addtocws for Binary mode Latch C

src/qrcode.ps, tests/ps_tests/rectangularmicroqrcode.ps, tests/ps_tests/test.ps
This suggests using N mode if input all numeric, or A mode if input all alphanumeric, apart from just using B, which allows for instance reproducing Figure 1 of ISO/IEC JTC1/SC31N000 (Draft 2018-6-8).
It's also an excuse to ask if you could confirm the changes from draft 2018-6-8 to values in Table 3 "Number of bits of character count indicator" for
R7x43 alphanumeric (3 bits from 4)
R11x27 numeric (4 bits from 5)
R13x43 numeric (6 bits from 7)
(and also whether the worked example in Annex H H.2 which uses R11x27 was revised accordingly).
These changes make sense in that that's all that's needed to hold the largest possible values for these cases. However I notice that the R13x77 numeric value hasn't changed from 8 bits (7 bits would suffice for max 123 numerics).
Whenever (and if!) you …
=> rectangularmicroqrcode: use N if all numeric, A if all alphanumeric

src/symbol.ps
[The USPS created another FIM mark, named FIM E, with the binary code 101000101.](https://pe.usps.com/text/dmm300/202.htm#ep1123678)
I *think* I've got the encoding right - I've tested it by comparing it side-by-side (but vertically, so misaligned bars would be very noticeable) against the FIM-D (which has every bar the FIM-E does and then some) and it looks visually correct, but it's possible I've made a mistake in encoding it.
Here's an example output:
.
=> Add USPS FIM E mark

src/dotcode.ps, tests/ps_tests/dotcode.ps
As the macro codewords are Code Set B, add Latch B when macro header detected (otherwise e.g. `10 100 moveto ([\)>^03005^029101^030^004) (parse) /dotcode /uk.co.terryburton.bwipp findresource exec` and `50 100 moveto ((97)171617) () /gs1dotcode /uk.co.terryburton.bwipp findresource exec` give the same result).
Also add the XX digits for macro 100 which were being skipped (could alternatively adjust the increment to `i` from 6 to 4 and leave encoding them to the loop but thinking it's probably clearer to deal with them immediately (also matches what Zint produces!)).
=> dotcode: macros: add latch B, include XX digits

src/dotcode.ps, tests/ps_tests/dotcode.ps
Handles CRLF when doing Shift B in Code Set C or A, otherwise e.g. `10 100 moveto (12a^013^010) (parse) /dotcode /uk.co.terryburton.bwipp findresource exec` and `10 100 moveto (^001a^009^013^010) (parse) /dotcode /uk.co.terryburton.bwipp findresource exec` will fail.
=> dotcode: handle Shift B CRLF in encC and encA

src/qrcode.ps, tests/ps_tests/microqrcode.ps
The `Bexcl` set was missing `0xA0` and `0xEC-0xFF` which would cause e.g. `10 100 moveto (^128) (parse) /microqrcode /uk.co.terryburton.bwipp findresource exec` to fail as the `numBs` would be zero causing the M1 and M2 versions not to be excluded in the "Derive optimal sequence" loop.
Rather than just add the missing values, the proposed change removes `Bexcl` altogether and instead sets `numBs` (and `nextBs`) in a post-loop based on the other exclusive sets. This has the advantage of not having to account for whether byte sequences overlap with Kanji or not, and should therefore be accurate.
=> qrcode: calculate numBs from "not others" to avoid Kanji overlap

src/qrcode.ps, tests/ps_tests/qrcode.ps
Fixes regression introduced by PR https://github.com/bwipp/postscriptbarcode/pull/179 not taking into account ECIs - needs to exclude `isECI` also in `numBs`/`nextBs` calculation loop (sigh).
=> qrcode: ECI regression fix (PR #179 [88510ab])

src/bc412.ps, tests/ps_tests/bc412.ps, tests/ps_tests/test.ps
For bc412 `(semi)` implements check digit calculation and placement (2nd char) based on SEMI T1-95 spec, with length 7-18 validation.
Also stop char length typo 2 -> 3.
=> bc412: semi: SEMI T1-95 check digit calc & pos

contrib/development/build-qr-mode-optim-arrs.php, src/qrcode.ps, tests/ps_tests/microqrcode.ps, tests/ps_tests/qrcode.ps, tests/ps_tests/rectangularmicroqrcode.ps
Partly addresses bwipp-js issue [#237](https://github.com/metafloor/bwip-js/issues/237) by adding `A or N` inclusive sum and in mode 0:
-  moves checking for N mode before checking for A mode and uses new `mode0forceN` array for `N before E` instead of `numN ge 1` check
-  checks `A or N` before B and E instead of just A
and in mode B:
- chooses A for short `A or N` sequences at end that only contain smallish N sequences (restrictions required to avoid other unwanted switches)
Overall the changes should improve some encodations without disimproving others (hopefully).
=> qrcode optimize: partly addresses bwipp-js #237 by adding A or N inclusive sum

src/msi.ps, tests/ps_tests/msi.ps, tests/ps_tests/test.ps
Re #17 for `msi` allow all `checktype`s containing `mod11` on checking when `badmod11` set (commit [56ac0e5]).
=> msi: allow any `checktype` containing mod11 if `badmod11` (#17)

src/msi.ps, tests/ps_tests/msi.ps
For `msi`, as giving input that results in a mod11 check digit of 10 without specifying `badmod11` causes a PS fail later, trap it ([#17](https://github.com/bwipp/postscriptbarcode/issues/17#issuecomment-1493082368)).
=> msi: Trap mod11 check digit is 10 but `badmod11` not given (#17)

src/auspost.ps, tests/ps_tests/auspost.ps, tests/ps_tests/test.ps
For `auspost`, add check that data length at least 10 (avoids PS fail) (#17).
=> auspost: Check data length at least 10 (#17)

src/code11.ps, tests/ps_tests/code11.ps, tests/ps_tests/test.ps
For `code11`, add check that data isn't empty (avoids PS fail when `validatecheck` given) (https://github.com/bwipp/postscriptbarcode/issues/17).
=> code11: Check for empty data (#17)

src/japanpost.ps, tests/ps_tests/japanpost.ps, tests/ps_tests/test.ps
For `japanpost`, add check that data isn't empty (avoids PS fail) (https://github.com/bwipp/postscriptbarcode/issues/17), plus typos on `BadCharacter` check.
=> japanpost: Check for empty data, plus BadCharacter typos (#17)

src/daft.ps, tests/ps_tests/daft.ps, tests/ps_tests/test.ps
For `daft`, add check that data isn't empty (avoids PS fail) (https://github.com/bwipp/postscriptbarcode/issues/17).
=> daft: Check for empty data (#17)

src/code2of5.ps, tests/ps_tests/code2of5.ps, tests/ps_tests/test.ps
For `code2of5` (and `industrial2of5`, `iata2of5`, `matrix2of5`, `coop2of5`, `datalogic2of5`), add check that data isn't empty (avoids PS fail when `validatecheck` given) (https://github.com/bwipp/postscriptbarcode/issues/17).
=> code2of5(/industrial/iata/matrix/coop/datalogic): Check for empty data (#17)

src/databaromni.ps, src/databarstacked.ps, src/databartruncated.ps, tests/ps_tests/databaromni.ps, tests/ps_tests/databarstacked.ps, tests/ps_tests/databartruncated.ps
For `databaromni`, `databarstacked` and `databartruncated`, move length check before BadAI check to avoid PS fail on BadAI `getinterval` (#17)
=> databaromni/stacked/truncated: Move length check before BadAI check (#17)

src/ean14.ps, tests/ps_tests/ean14.ps, tests/ps_tests/test.ps
For `ean14`, move length check before BadAI check to avoid PS fail on BadAI `getinterval` (#17)
=> ean14: Move length check before BadAI check (#17)

src/gs1-cc.ps, tests/ps_tests/gs1-cc.ps
For `gs1-cc`, set `cccolumns` to arbitrary value (2) when `lintype` not set to avoid PS fail on `lintypecccolumns` lookup (#17)
=> gs1-cc: Set `cccolumns` when `lintype` not set to avoid PS fail (#17)

src/bc412.ps, tests/ps_tests/bc412.ps
For `bc412`, add check that data isn't empty (avoids PS fail when `validatecheck` given and not semi) (#17).
=> bc412: Check for empty data to avoid PS fail (#17)

src/plessey.ps, tests/ps_tests/plessey.ps, tests/ps_tests/test.ps
For `plessey`,  add check that data isn't empty (avoids PS fail when `validatecheck` given) (#17).
=> plessey: Check for empty data to avoid PS fail when `validatecheck` given (#17)

src/posicode.ps, tests/ps_tests/posicode.ps, tests/ps_tests/test.ps
For `posicode`, add checks for version and for input data if limited to avoid various PS fails (#17).
=> posicode: Add checks for version and for input data if limited to avoid PS fails (#17)

src/rationalizedCodabar.ps, tests/ps_tests/rationalizedCodabar.ps, tests/ps_tests/test.ps
For `rationalizedCodabar`, check length at least 2 (or 3 if `validatecheck` given) to avoid a PS fail in the `charvals` `getinterval` (#17).
=> rationalizedCodabar: Add length check to avoid PS fail (#17)

src/sscc18.ps, tests/ps_tests/sscc18.ps, tests/ps_tests/test.ps
For `sscc18`, move length check before BadAI check to avoid PS fail on BadAI `getinterval` (#17)
=> sscc18: Move length check before BadAI check to avoid PS fail (#17)

src/qrcode.ps, tests/ps_tests/qrcode.ps
Avoids initial zero-length byte sequence when input starts with 6+ digits followed by kanji by adding `mode0NbeforeB NbeforeK` -> N check in mode -1.
Previously would -> B in mode -1 then bounce immediately to -> N in mode B (due to `modeBNbeforeK NbeforeK` check).
Now 4+ digits will cause mode N to be used, same as `NbeforeB`, which seems reasonable and conservative I think given that deciding between mode N and mode B.
Alternatively could just check for `charslen` being zero when looping through the sequences and skip if so... more defensive in case there're other ways 0-length sequences could arise but somewhat hacky?
(Discovered this when adding a test case to Zint for the "invalid byte pairs in Kanji mode" fix [8fcbe7c]. Note the barcode still decodes ok, just unnecessary bloat.)
=> qrcode: Avoid initial B0 seq when input starts 6+ digits then kanji

src/code128.ps, tests/ps_tests/code128.ps, tests/ps_tests/gs1-128.ps
Avoid extraneous CodeC switch (with immediate switch back to CodeA/B) by re-checking digit runlength >= 4 after enca/encb push
Also simplify `numsscr` to return only `nums` as `nchars` unused (cf codablockf and code16k which similarly could be simplified)
=> code128: Avoid extraneous CodeC switch

src/maxicode.ps.src, tests/ps_tests/maxicode.ps.test
Data from ECI and following added back later.
Also field identifier barlen test 7 -> 9 and check that
"yy" digits. Also error if pcode empty.
=> maxicode: Exit SCM loop on 1st ECI to avoid ECIs being nulled

src/parseinput.ps.src, tests/ps_tests/parseinput.ps.test
and error if truncated before erroring for truncated FNC
=> parseinput: allow for double caret at end

src/codablockf.ps.src, tests/ps_tests/codablockf.ps.test
(Found via "backend/tests/test_bwipp" - same bug in zint.)
=> codablockf: ignore 2nd byte of FNC4 when counting digits in `numsscr`
